### ISSUE TITLE
How do i use it

### ISSUE THREAD

**Issue by MarioGaming298** [iomintz/acnh-backup-restore#1]
I'm downloaded animal crossing on my switch console and I'm trying to save my progress but ofc Checkpoint doesn't work with it. Luckly I found the program you made but uh, how do you use it lmao. is there like a payload I use or... :/

**Comment by ioistired** [comment]
If you have the Homebrew App Store already, you can get it from there. Otherwise, download the acnh-backup-restore.nro file from the [releases](https://github.com/iomintz/acnh-backup-restore/releases) page and put it in your switch/ folder on your SD card. 

When you open the software, you can press "B" to backup your save, or "A" to pick a save file to restore.

**Comment by MarioGaming298** [comment]
ok thanks

**Comment by ioistired** [comment]
I've added installation and usage sections to the README for you.

**Comment by Permamiss** [comment]
@iomintz I have an unmodified Nintendo Switch. When I browse my microSD Card, I only see a "Nintendo" folder, and no "switch" folder inside it or anything. Does this work on unmodified consoles?

**Comment by ioistired** [comment]
@Permamiss no. There is currently no way to back up ACNH saves on an unmodified Switch.

**Comment by Permamiss** [comment]
Damn. Thank you for responding, I've been trying to figure out a way to do this unmodified for a while to no avail.

**Comment by ioistired** [comment]
Nintendo has mentioned they will add an alternative backup system to New Horizons, but it remains to be see whether it'll actually happen, and if it will, whether it will be [gimped in some way](https://nintendosoup.com/animal-crossing-new-horizons-save-data-backup-will-only-work-once/).
